///////////////////////////////////////////////////////////////////
//Generated by ex4 to mq4 decompile Service                      // 
//Website:                                                       //
//E-mail : jlk2k3@gmail.com ; decompiler.ex4tomq4@gmail.com      //
///////////////////////////////////////////////////////////////////
#property copyright "Copyright 2013, bamsbung@inc"
#property link      "http://www.bamsbung.com"

//extern int Acount_Number = 0;
//string Gs_80 = "2014.09.30 00:00";
extern int Magic = 123456;
extern string _ = "=======================================";
extern bool Single = TRUE;
extern bool MM = FALSE;
extern double Risk = 0.01;
extern double Single_Lot = 0.11;
extern int Single_TP = 10;
extern int Single_SL = 0;
extern int Single_TS = 0;
extern int Single_TS_Start = 0;
extern bool Single_Close_By_Signal = TRUE;
bool Gi_144 = 2;
extern string __ = "=======================================";
extern bool Hedging = TRUE;
extern double Hedging_Lot = 0.12;
extern int Hedging_TP = 10;
extern double Hedging_Multiplier = 1.5;
extern double Hedging_TP_Money = 10.0;
extern bool Hedging_Close_By_Signal = TRUE;
extern int Hedging_Max = 10;
bool Gi_196 = FALSE;
int Gi_200 = 2;
extern string ___ = "=======================================";
extern bool AveraPlus = TRUE;
extern double AveraPlus_Lot = 0.13;
extern int AveraPlus_Step = 5;
extern int AveraPlus_Max = 5;
extern int AveraPlus_TP = 40;
extern int AveraPlus_SL = 0;
extern int AveraPlus_TS = 0;
extern int AveraPlus_TS_Start = 0;
extern bool AveraPlus_Close_By_Signal = TRUE;
bool Gi_252 = 2;
bool Gi_unused_256 = 2;
bool Gi_260 = TRUE;
bool Gi_264 = 2;
extern string ____ = "=======================================";
extern bool AveraMinus = TRUE;
extern double AveraMinus_Lot = 0.14;
extern double AveraMinus_Multiplier = 1.5;
extern int AveraMinus_Step = 20;
extern int AveraMinus_Max = 5;
extern int AveraMinus_TP = 20;
extern int AveraMinus_SL = 0;
extern double AveraMinus_TP_Money = 10.0;
extern bool AveraMinus_Close_By_Signal = FALSE;
bool Gi_324 = 2;
bool Gi_328 = 2;
bool Gi_332 = FALSE;
bool Gi_336 = FALSE;
extern string _____ = "=======================================";
extern string Time_Info = "Time Trading Server";
extern int OpenHour = 0;
extern int CloseHour = 24;
extern string Coment = " bamsbung ";
extern int Sift = 1;
extern int Sift_Close = 0;
bool Gi_380 = FALSE;
string Gs_unused_384 = "terminal_dir \\ experts \\ files  ";
string Gs_unused_392 = "terminal_dir \\ tester \\ files   ";
double Gd_400;
double G_minlot_416;
double G_maxlot_424;
double G_spread_432;
double G_stoplevel_440;
double Gd_456 = 2.0;
double G_time_464 = 0.0;
double Gd_472 = 2.0;
double Gd_480 = 0.0;
bool Gi_unused_488 = FALSE;

// E37F0136AA3FFAF149B351F6A4C948E9
int init() {
   if (Digits == 5 || Digits == 3 || Symbol() == "GOLD" || Symbol() == "GOLD." || Symbol() == "GOLDm") Gd_400 = 10.0 * Point;
   else Gd_400 = Point;
   if (!IsExpertEnabled()) Alert("EXPERT ASVISORS MASIH DISABLE !");
   if (!IsTradeAllowed()) Alert("ALLOW LIVE TRADING BELUM DI CENTANG !");
   return (0);
}
	 	 			 		    			  	 					 	    	 	 				  	  			   								 	 		  	   	 	 			 		  				     	  				 	 	 	 	  	 		     				 		  		  	   	  		 	 	  
// 52D46093050F38C27267BCE42543EF60
int deinit() {
   Comment("");
   return (0);
}
	 		 					 		 	 	   			 		  	  		 		 		   					      		 				  	   			 			 	   	   	  	 	    	 	 		  		   	 	  	    				 	 	 	 	   			 		 			  		 
// EA2B2676C28C0DB26D39331A336C6B92
int start() {
   bool Li_16;
   bool Li_20;
   string Ls_unused_28;
   bool Li_36;
   bool Li_40;
   int magic_44;
   /*string Ls_0 = "2014.03.25";
   int str2time_8 = StrToTime(Ls_0);
   if (TimeCurrent() >= str2time_8) {
      Alert("Expired ... Please contact Bamsbung.com");
      return (0);
   }*/
   int ticket_12 = 0;
   if (f0_4()) {
      if (f0_1()) {
         G_minlot_416 = MarketInfo(Symbol(), MODE_MINLOT);
         G_maxlot_424 = MarketInfo(Symbol(), MODE_MAXLOT);
         G_spread_432 = MarketInfo(Symbol(), MODE_SPREAD);
         G_stoplevel_440 = MarketInfo(Symbol(), MODE_STOPLEVEL);
         Li_16 = FALSE;
         Li_20 = FALSE;
         for (int Li_24 = Sift; Li_24 < 3; Li_24++) {
            if (Time[Li_24] > G_time_464) {
               if (ObjectGet("Bams-bung:" + Time[Li_24], OBJPROP_COLOR) == 255.0) {
                  Gd_456 = 1;
                  G_time_464 = Time[Li_24];
                  break;
               }
               if (ObjectGet("Bams-bung:" + Time[Li_24], OBJPROP_COLOR) == 65280.0) {
                  Gd_456 = 0;
                  G_time_464 = Time[Li_24];
                  break;
               }
            }
         }
         Ls_unused_28 = "WAIT";
         if (G_time_464 > Time[Sift + 1]) {
            if (Gd_456 == 1.0) {
               Li_20 = TRUE;
               Ls_unused_28 = "SINYAL SELL";
            }
            if (Gd_456 == 0.0) {
               Li_16 = TRUE;
               Ls_unused_28 = "SINYAL BUY";
            }
         } else Ls_unused_28 = "  Expired";
         Li_36 = FALSE;
         Li_40 = FALSE;
         for (Li_24 = Sift_Close; Li_24 < 3; Li_24++) {
            if (Time[Li_24] > Gd_480) {
               if (ObjectGet("Bams-bung:" + Time[Li_24], OBJPROP_COLOR) == 255.0) {
                  Gd_472 = 1;
                  G_time_464 = Time[Li_24];
                  break;
               }
               if (ObjectGet("Bams-bung:" + Time[Li_24], OBJPROP_COLOR) == 65280.0) {
                  Gd_472 = 0;
                  G_time_464 = Time[Li_24];
                  break;
               }
            }
         }
         if (Gd_480 > Time[Sift + 1]) {
            if (Gd_472 == 1.0) Li_40 = TRUE;
            if (Gd_472 == 0.0) Li_36 = TRUE;
         }
         f0_11(1, "NamaEA", WindowExpertName());
         f0_11(2, "No Account ", AccountNumber());
         f0_11(3, "Leverage ", " 1 : " + DoubleToStr(AccountLeverage(), 0));
         f0_11(4, "Balance", DoubleToStr(AccountBalance(), 2));
         f0_11(5, "Equity", DoubleToStr(AccountEquity(), 2));
         f0_11(7, "Profit ", DoubleToStr(f0_9("pfb", Magic) + f0_9("pfs", Magic), 2));
         f0_11(6, "copyright Bamsbung inc@ 2013 ", DoubleToStr(Hour(), 0));
         magic_44 = Magic;
         if (Single) {
            magic_44 = Magic + 123;
            if (Single_Close_By_Signal) {
               if (Li_36 || Li_16) f0_6(OP_SELL, magic_44);
               if (Li_40 || Li_20) f0_6(OP_BUY, magic_44);
            }
            if (MM) Single_Lot = AccountEquity() / 1000.0 * Risk;
            if (f0_0()) {
               if (Li_16) {
                  if (f0_9("b", magic_44) < 1.0 && Gi_144 != FALSE) ticket_12 = OrderSend(Symbol(), OP_BUY, f0_8(Single_Lot), Ask, 3, 0, 0, Coment + " Single_OP", magic_44, 0, Blue);
                  if (ticket_12 > 0) Gi_144 = FALSE;
               } else {
                  if (Li_20) {
                     if (f0_9("s", magic_44) < 1.0 && Gi_144 != TRUE) ticket_12 = OrderSend(Symbol(), OP_SELL, f0_8(Single_Lot), Bid, 3, 0, 0, Coment + " Single_OP", magic_44, 0, Red);
                     if (ticket_12 > 0) Gi_144 = TRUE;
                  }
               }
            }
            f0_2(0, "S-", Single_TP, magic_44);
            f0_2(1, "S-", Single_TP, magic_44);
            f0_10("S-", Single_SL, magic_44);
            if (Bid - f0_9("pb", magic_44) >= (Single_TS_Start + Single_TS) * Gd_400) f0_7(0, "S-", Single_TS, magic_44);
            if (f0_9("ps", magic_44) - Ask >= (Single_TS_Start + Single_TS) * Gd_400) f0_7(1, "S-", Single_TS, magic_44);
            f0_7(2, "S-", Single_TS, magic_44);
         }
         if (Hedging) {
            magic_44 = Magic + 456;
            if (Hedging_Close_By_Signal && f0_9("pfb", magic_44) + f0_9("pfs", magic_44) > 0.0) {
               if (Li_16 || Li_36 && f0_9("tlb", magic_44) < f0_9("tls", magic_44)) Gi_196 = TRUE;
               if (Li_20 || Li_40 && f0_9("tlb", magic_44) > f0_9("tls", magic_44)) Gi_196 = TRUE;
            }
            if (f0_0() && f0_9("b", magic_44) + f0_9("s", magic_44) < 1.0) {
               Gi_196 = FALSE;
               if (Li_16 && Gi_200 != 0) {
                  ticket_12 = OrderSend(Symbol(), OP_BUY, f0_8(Hedging_Lot), Ask, 3, 0, 0, Coment + " Hedging", magic_44, 0, Blue);
                  Gi_200 = 0;
               } else {
                  if (Li_20 && Gi_200 != 1) {
                     ticket_12 = OrderSend(Symbol(), OP_SELL, f0_8(Hedging_Lot), Bid, 3, 0, 0, Coment + " Hedging", magic_44, 0, Red);
                     Gi_200 = 1;
                  }
               }
            }
            if (f0_9("pfb", magic_44) + f0_9("pfs", magic_44) >= Hedging_TP_Money) Gi_196 = TRUE;
            if (Gi_196) {
               f0_6(OP_BUY, magic_44);
               f0_6(OP_SELL, magic_44);
               return;
            }
            if (Hedging_Max > f0_9("b", magic_44) + f0_9("s", magic_44)) {
               if (f0_9("tip", magic_44) == 0.0 && Li_20) ticket_12 = OrderSend(Symbol(), OP_SELL, f0_8(f0_9("lb", magic_44) * Hedging_Multiplier + 0.004), Bid, 3, 0, 0, Coment + " Hedging", magic_44, 0, Red);
               if (f0_9("tip", magic_44) == 1.0 && Li_16) ticket_12 = OrderSend(Symbol(), OP_BUY, f0_8(f0_9("ls", magic_44) * Hedging_Multiplier + 0.004), Ask, 3, 0, 0, Coment + " Hedging", magic_44, 0, Blue);
            }
            if (f0_9("b", magic_44) + f0_9("s", magic_44) <= 1.0) {
               f0_2(0, "H-", Hedging_TP, magic_44);
               f0_2(1, "H-", Hedging_TP, magic_44);
            } else Gi_200 = 2;
         }
         if (AveraPlus) {
            magic_44 = Magic + 678;
            if (Li_16) Gi_252 = FALSE;
            if (Li_20) Gi_252 = TRUE;
            if (AveraPlus_Close_By_Signal) {
               if (Gi_252 == FALSE || Li_36) f0_6(OP_SELL, magic_44);
               if (Gi_252 == TRUE || Li_40) f0_6(OP_BUY, magic_44);
            }
            if (AveraPlus_Max <= f0_9("b", magic_44)) Gi_260 = FALSE;
            if (AveraPlus_Max <= f0_9("s", magic_44)) Gi_260 = FALSE;
            if (f0_0() && f0_9("b", magic_44) + f0_9("s", magic_44) < 1.0) {
               f0_3("avg+" + "TPB", 99999, Fuchsia, STYLE_DOT);
               f0_3("avg+" + "TPS", 0, Fuchsia, STYLE_DOT);
               f0_3("avg+" + "SLB", 0, Red, STYLE_DOT);
               f0_3("avg+" + "SLS", 99999, Red, STYLE_DOT);
               Gi_unused_256 = FALSE;
               Gi_260 = TRUE;
               if (Gi_252 == FALSE && Gi_264 != FALSE) {
                  ticket_12 = OrderSend(Symbol(), OP_BUY, f0_8(AveraPlus_Lot), Ask, 3, 0, 0, Coment + " Avg Plus", magic_44, 0, Blue);
                  Gi_264 = FALSE;
               } else {
                  if (Gi_252 == TRUE && Gi_264 != TRUE) {
                     ticket_12 = OrderSend(Symbol(), OP_SELL, f0_8(AveraPlus_Lot), Bid, 3, 0, 0, Coment + " Avg Plus", magic_44, 0, Red);
                     Gi_264 = TRUE;
                  }
               }
            }
            if (f0_9("tip", magic_44) == 0.0 && Gi_252 == FALSE && Gi_260 && AveraPlus_Max > f0_9("b", magic_44) && Ask - f0_9("pb", magic_44) >= AveraPlus_Step * Gd_400) ticket_12 = OrderSend(Symbol(), OP_BUY, f0_8(AveraPlus_Lot), Ask, 3, 0, 0, Coment + " Avg Plus", magic_44, 0, Blue);
            if (f0_9("tip", magic_44) == 1.0 && Gi_252 == TRUE && Gi_260 && AveraPlus_Max > f0_9("s", magic_44) && f0_9("ps", magic_44) - Bid >= AveraPlus_Step * Gd_400) ticket_12 = OrderSend(Symbol(), OP_SELL, f0_8(AveraPlus_Lot), Bid, 3, 0, 0, Coment + " Avg Plus", magic_44, 0, Red);
            f0_5(magic_44);
            f0_3("avg+" + "TPB", f0_9("minb", magic_44) + AveraPlus_TP * Gd_400, Fuchsia, STYLE_DOT);
            f0_3("avg+" + "TPS", f0_9("maxs", magic_44) - AveraPlus_TP * Gd_400, Fuchsia, STYLE_DOT);
            f0_3("avg+" + "SLB", f0_9("maxb", magic_44) - AveraPlus_SL * Gd_400, Red, STYLE_DOT);
            f0_3("avg+" + "SLS", f0_9("mins", magic_44) + AveraPlus_SL * Gd_400, Red, STYLE_DOT);
            if (f0_9("minb", magic_44) + (AveraPlus_TS_Start + AveraPlus_TS) * Gd_400 <= Bid) f0_7(0, "AP-", AveraPlus_TS, magic_44);
            if (f0_9("maxs", magic_44) - (AveraPlus_TS_Start + AveraPlus_TS) * Gd_400 >= Ask) f0_7(1, "AP-", AveraPlus_TS, magic_44);
            f0_7(2, "AP-", AveraPlus_TS, magic_44);
         }
         if (!(AveraMinus)) return (0);
         magic_44 = Magic + 910;
         if (f0_9("b", magic_44) == 0.0) Gi_332 = FALSE;
         if (f0_9("s", magic_44) == 0.0) Gi_336 = FALSE;
         if (f0_9("pfb", magic_44) >= AveraMinus_TP_Money && f0_9("b", magic_44) > 1.0) {
            Gi_332 = TRUE;
            Print("TP BUY MONEY AVERA MINUS");
         }
         if (f0_9("pfs", magic_44) >= AveraMinus_TP_Money && f0_9("s", magic_44) > 1.0) {
            Gi_336 = TRUE;
            Print("TP SELL MONEY AVERA MINUS");
         }
         if (Gi_332) f0_6(OP_BUY, magic_44);
         else {
            if (Gi_336) f0_6(OP_SELL, magic_44);
            else {
               if (f0_0()) {
                  if (Li_16 && Gi_324 != FALSE && f0_9("b", magic_44) == 0.0) {
                     Gi_328 = FALSE;
                     ticket_12 = OrderSend(Symbol(), OP_BUY, f0_8(AveraMinus_Lot), Ask, 3, 0, 0, Coment + " Avg Minus", magic_44, 0, Blue);
                     Gi_324 = FALSE;
                  } else {
                     if (Li_20 && Gi_324 != TRUE && f0_9("s", magic_44) == 0.0) {
                        Gi_328 = TRUE;
                        ticket_12 = OrderSend(Symbol(), OP_SELL, f0_8(AveraMinus_Lot), Bid, 3, 0, 0, Coment + " Avg Minus", magic_44, 0, Red);
                        Gi_324 = TRUE;
                     }
                  }
               }
               if (f0_9("b", magic_44) > 0.0 && AveraMinus_Max > f0_9("b", magic_44) && f0_9("pb", magic_44) - Ask >= AveraMinus_Step * Gd_400) ticket_12 = OrderSend(Symbol(), OP_BUY, f0_8(f0_9("lb", magic_44) * AveraMinus_Multiplier + 0.004), Ask, 3, 0, 0, Coment + " Avg Minus", magic_44, 0, Blue);
               if (f0_9("s", magic_44) > 0.0 && AveraMinus_Max > f0_9("s", magic_44) && Bid - f0_9("ps", magic_44) >= AveraMinus_Step * Gd_400) ticket_12 = OrderSend(Symbol(), OP_SELL, f0_8(f0_9("ls", magic_44) * AveraMinus_Multiplier + 0.004), Bid, 3, 0, 0, Coment + " Avg Minus", magic_44, 0, Red);
               if (AveraMinus_Close_By_Signal) {
                  if (Gi_328 == FALSE || Li_36 && f0_9("pfs", magic_44) > 0.0) {
                     f0_6(OP_SELL, magic_44);
                     Print("SELL CLOSE BY SINYAL  AVERA MINUS");
                  }
                  if (Gi_328 == TRUE || Li_40 && f0_9("pfb", magic_44) > 0.0) {
                     f0_6(OP_BUY, magic_44);
                     Print("BUY CLOSE BY SINYAL  AVERA MINUS");
                  }
               }
               if (f0_9("b", magic_44) == 1.0) f0_2(0, "Min-", AveraMinus_TP, magic_44);
               if (f0_9("s", magic_44) != 1.0) return (0);
               f0_2(1, "Min-", AveraMinus_TP, magic_44);
            }
         }
      }
   }
   return (0);
}
		 		   	 		 	 				    		 	  		 		 		  	 	 	   	 		 	  		  			 	 	 	 	  		  		 	 	  	 	  		  	 		 	   		  				 	 			   			   	 	 	 	 	     			   
// 07CC694B9B3FC636710FA08B6922C42B
int f0_0() {
   bool Li_ret_0 = FALSE;
   if (OpenHour < CloseHour) {
      if (Hour() >= OpenHour && Hour() <= CloseHour) Li_ret_0 = TRUE;
   } else {
      if (OpenHour > CloseHour)
         if (Hour() >= OpenHour || Hour() <= CloseHour) Li_ret_0 = TRUE;
   }
   return (Li_ret_0);
}
	 	  			 	  	 	    				  	 		  	  	  		 	 	 			 	  	 		  		   	 	 	 	 		  		  	 	 		 	 		  		 	  	 			  		    	 	   			   			 	 	 	 	 					   			
// B2F5FF47436671B6E533D8DC3614845D
double f0_9(string As_0, int A_magic_8) {
   double Ld_12 = 0;
   double Ld_20 = 0;
   double Ld_ret_28 = 0;
   double Ld_36 = 0;
   double Ld_44 = 0;
   double Ld_52 = 0;
   double Ld_60 = 0;
   double Ld_68 = 0;
   double Ld_76 = 0;
   double Ld_84 = 0;
   double Ld_92 = 0;
   double Ld_100 = 0;
   double Ld_108 = 0;
   double Ld_116 = 0;
   double Ld_124 = 0;
   double Ld_132 = 0;
   double Ld_140 = 0;
   double Ld_148 = 0;
   double Ld_156 = 4;
   double Ld_164 = 0;
   double Ld_172 = 0;
   double Ld_180 = 99999;
   double Ld_188 = 0;
   double Ld_196 = 0;
   double Ld_204 = 0;
   double Ld_unused_212 = 0;
   double Ld_220 = 99999;
   double Ld_228 = 0;
   double Ld_236 = 0;
   double Ld_244 = 99999;
   for (int pos_252 = 0; pos_252 < OrdersTotal(); pos_252++) {
      OrderSelect(pos_252, SELECT_BY_POS, MODE_TRADES);
      if (OrderSymbol() == Symbol() || As_0 == "all" && OrderMagicNumber() == A_magic_8) {
         if (OrderType() == OP_BUY) {
            Ld_196 = OrderTicket();
            Ld_180 = MathMin(Ld_180, OrderOpenPrice());
            Ld_220 = MathMin(Ld_220, OrderOpenPrice());
            Ld_236 = MathMax(Ld_236, OrderOpenPrice());
            Ld_12++;
            Ld_36 = OrderOpenPrice();
            Ld_52 = OrderLots();
            Ld_68 = OrderTakeProfit();
            Ld_84 += OrderLots();
            Ld_108 += OrderProfit();
            Ld_148 = OrderLots();
            Ld_156 = 0;
            Ld_164 = OrderOpenPrice();
            Ld_172 = OrderLots();
         }
         if (OrderType() == OP_SELL) {
            Ld_204 = OrderTicket();
            Ld_188 = MathMax(Ld_188, OrderOpenPrice());
            Ld_228 = MathMax(Ld_228, OrderOpenPrice());
            Ld_244 = MathMin(Ld_244, OrderOpenPrice());
            Ld_20++;
            Ld_44 = OrderOpenPrice();
            Ld_60 = OrderLots();
            Ld_76 = OrderTakeProfit();
            Ld_92 += OrderLots();
            Ld_116 += OrderProfit();
            Ld_148 = OrderLots();
            Ld_156 = 1;
            Ld_164 = OrderOpenPrice();
            Ld_172 = OrderLots();
         }
         if (OrderType() == OP_SELLSTOP) Ld_100++;
         if (OrderType() == OP_BUYSTOP) Ld_124++;
         if (OrderType() == OP_SELLLIMIT) Ld_140++;
         if (OrderType() == OP_BUYLIMIT) Ld_132++;
      }
   }
   if (As_0 == "minb") Ld_ret_28 = Ld_220;
   if (As_0 == "maxs") Ld_ret_28 = Ld_228;
   if (As_0 == "mins") Ld_ret_28 = Ld_244;
   if (As_0 == "maxb") Ld_ret_28 = Ld_236;
   if (As_0 == "all") Ld_ret_28 = Ld_12 + Ld_20;
   if (As_0 == "b") Ld_ret_28 = Ld_12;
   if (As_0 == "s") Ld_ret_28 = Ld_20;
   if (As_0 == "pbr") Ld_ret_28 = Ld_180;
   if (As_0 == "pst") Ld_ret_28 = Ld_188;
   if (As_0 == "pb") Ld_ret_28 = Ld_36;
   if (As_0 == "ps") Ld_ret_28 = Ld_44;
   if (As_0 == "ls") Ld_ret_28 = Ld_60;
   if (As_0 == "lb") Ld_ret_28 = Ld_52;
   if (As_0 == "tps") Ld_ret_28 = Ld_76;
   if (As_0 == "tpb") Ld_ret_28 = Ld_68;
   if (As_0 == "tls") Ld_ret_28 = Ld_92;
   if (As_0 == "tlb") Ld_ret_28 = Ld_84;
   if (As_0 == "pfs") Ld_ret_28 = Ld_116;
   if (As_0 == "pfb") Ld_ret_28 = Ld_108;
   if (As_0 == "tikb") Ld_ret_28 = Ld_196;
   if (As_0 == "tiks") Ld_ret_28 = Ld_204;
   if (As_0 == "lt") Ld_ret_28 = Ld_148;
   if (As_0 == "ss") Ld_ret_28 = Ld_100;
   if (As_0 == "bs") Ld_ret_28 = Ld_124;
   if (As_0 == "sl") Ld_ret_28 = Ld_140;
   if (As_0 == "bl") Ld_ret_28 = Ld_132;
   if (As_0 == "lp") Ld_ret_28 = Ld_164;
   if (As_0 == "tip") Ld_ret_28 = Ld_156;
   if (As_0 == "ll") Ld_ret_28 = Ld_172;
   return (Ld_ret_28);
}
	  	  	  							  	 	 		 		 		     	  			  		 			 	   		 	 	 				  				      				       	 	 				 		 	  					 				 			 		    					  				 		 	 		 	
// 4618C2B26E9E222B2CF19471E1F2AF8C
void f0_3(string A_name_0, double Ad_8, color A_color_16, int A_style_20) {
   int time_24 = Time[24];
   int datetime_28 = Time[0] + 60 * (5 * Period());
   double Ld_32 = Ad_8;
   string name_40 = " " + A_name_0;
   string name_48 = A_name_0;
   if (ObjectFind(name_40) != 0) ObjectCreate(name_40, OBJ_TREND, 0, 0, 0, 0, 0);
   else {
      ObjectMove(name_40, 0, time_24, Ad_8);
      ObjectMove(name_40, 1, datetime_28, Ld_32);
   }
   ObjectSet(name_40, OBJPROP_STYLE, A_style_20);
   ObjectSet(name_40, OBJPROP_COLOR, A_color_16);
   ObjectSet(name_40, OBJPROP_RAY, FALSE);
   if (ObjectFind(name_48) != 0) ObjectCreate(name_48, OBJ_TEXT, 0, time_24, Ad_8);
   else ObjectMove(name_48, 0, time_24, Ad_8);
   ObjectSetText(name_48, name_48, 6, "Arial", CLR_NONE);
   ObjectSet(name_48, OBJPROP_COLOR, A_color_16);
}
			 		 	         	 	 	     	  		 		 		  			  	  		 			    	 	   			    	 				   										 	       	 		 	   	   		   	   			    			    		 	 	  		
// 1CD979309246DCF03C76739887BA0AEC
void f0_2(int Ai_0, string As_4, int Ai_12, int A_magic_16) {
   double Ld_20 = ObjectGet(As_4 + "TPB", OBJPROP_PRICE1);
   double Ld_28 = ObjectGet(As_4 + "TPS", OBJPROP_PRICE1);
   for (int pos_36 = OrdersTotal() - 1; pos_36 >= 0; pos_36--) {
      OrderSelect(pos_36, SELECT_BY_POS, MODE_TRADES);
      if (OrderSymbol() == Symbol() && OrderMagicNumber() == A_magic_16) {
         if (OrderType() == OP_BUY || OrderType() == OP_BUYLIMIT || OrderType() == OP_BUYSTOP && Ai_0 == 0 && Ai_12 > 0 && Ld_20 == 99999.0) f0_3(As_4 + "TPB", OrderOpenPrice() + Ai_12 * Gd_400, Fuchsia, STYLE_DOT);
         if (OrderType() == OP_SELL || OrderType() == OP_SELLLIMIT || OrderType() == OP_SELLSTOP && Ai_0 == 1 && Ai_12 > 0 && Ld_28 == 0.0) f0_3(As_4 + "TPS", OrderOpenPrice() - Ai_12 * Gd_400, Fuchsia, STYLE_DOT);
      }
   }
   Ld_20 = ObjectGet(As_4 + "TPB", OBJPROP_PRICE1);
   Ld_28 = ObjectGet(As_4 + "TPS", OBJPROP_PRICE1);
   if (Bid > Ld_20 && Ai_0 == 0 && Ld_20 > 0.0) {
      f0_6(OP_BUY, A_magic_16);
      Print("BUY HIDEN TP " + As_4);
   }
   if (Ask < Ld_28 && Ai_0 == 1) {
      f0_6(OP_SELL, A_magic_16);
      Print("SELL HIDEN TP " + As_4);
   }
   if (f0_9("b", A_magic_16) == 0.0) f0_3(As_4 + "TPB", 99999, Red, STYLE_DOT);
   if (f0_9("s", A_magic_16) == 0.0) f0_3(As_4 + "TPS", 0, Red, STYLE_DOT);
}
			 		 		       		 	 	  	  	  					 		   		  	   	 			  	 	 	    		    						    							 	 	    	  	 		     	    	   	  				     		    	  	 	  	 
// B735E250FF5D58E98F3B38FCC92B6080
void f0_10(string As_0, int Ai_8, int A_magic_12) {
   double Ld_16 = ObjectGet(As_0 + "SLB", OBJPROP_PRICE1);
   double Ld_24 = ObjectGet(As_0 + "SLS", OBJPROP_PRICE1);
   for (int pos_32 = OrdersTotal() - 1; pos_32 >= 0; pos_32--) {
      OrderSelect(pos_32, SELECT_BY_POS, MODE_TRADES);
      if (OrderSymbol() == Symbol() && OrderMagicNumber() == A_magic_12) {
         if (OrderType() == OP_BUY || OrderType() == OP_BUYLIMIT || OrderType() == OP_BUYSTOP && Ai_8 > 0 && Ld_16 == 0.0) f0_3(As_0 + "SLB", OrderOpenPrice() - Ai_8 * Gd_400, Red, STYLE_DOT);
         if (OrderType() == OP_SELL || OrderType() == OP_SELLLIMIT || OrderType() == OP_SELLSTOP && Ai_8 > 0 && Ld_24 == 99999.0) f0_3(As_0 + "SLS", OrderOpenPrice() + Ai_8 * Gd_400, Red, STYLE_DOT);
      }
   }
   Ld_16 = ObjectGet(As_0 + "SLB", OBJPROP_PRICE1);
   Ld_24 = ObjectGet(As_0 + "SLS", OBJPROP_PRICE1);
   if (Bid < Ld_16) f0_6(OP_BUY, A_magic_12);
   if (Ask > Ld_24 && Ld_24 > 0.0) f0_6(OP_SELL, A_magic_12);
   if (f0_9("b", A_magic_12) == 0.0) f0_3(As_0 + "SLB", 0, Red, STYLE_DOT);
   if (f0_9("s", A_magic_12) == 0.0) f0_3(As_0 + "SLS", 99999, Red, STYLE_DOT);
}
				 	     		  	 	  		 	    	 	  			 	 							 			   	 	  		   						    		    				  		 		  	  	    					  	   			 			 	 		 	  						   	 		    	
// AA1AEB8DA792A08776A9CE8AF7FD5373
void f0_7(int Ai_0, string As_4, int Ai_12, int A_magic_16) {
   double Ld_20 = ObjectGet(As_4 + "SLB", OBJPROP_PRICE1);
   double Ld_28 = ObjectGet(As_4 + "SLS", OBJPROP_PRICE1);
   for (int pos_36 = OrdersTotal() - 1; pos_36 >= 0; pos_36--) {
      OrderSelect(pos_36, SELECT_BY_POS, MODE_TRADES);
      if (OrderSymbol() == Symbol() && OrderMagicNumber() == A_magic_16) {
         if (OrderType() == OP_BUY && Ai_0 == 0 && Ai_12 > 0 && Ld_20 < Bid - Ai_12 * Gd_400) f0_3(As_4 + "SLB", Bid - Ai_12 * Gd_400, Yellow, STYLE_DOT);
         if (OrderType() == OP_SELL && Ai_0 == 1 && Ai_12 > 0 && Ld_28 > Ask + Ai_12 * Gd_400) f0_3(As_4 + "SLS", Bid + Ai_12 * Gd_400, Yellow, STYLE_DOT);
      }
   }
   Ld_20 = ObjectGet(As_4 + "SLB", OBJPROP_PRICE1);
   Ld_28 = ObjectGet(As_4 + "SLS", OBJPROP_PRICE1);
   if (Bid < Ld_20) f0_6(OP_BUY, A_magic_16);
   if (Ask > Ld_28) f0_6(OP_SELL, A_magic_16);
   if (f0_9("b", A_magic_16) == 0.0) f0_3(As_4 + "SLB", 0, Red, STYLE_DOT);
   if (f0_9("s", A_magic_16) == 0.0) f0_3(As_4 + "SLS", 99999, Red, STYLE_DOT);
}
		 		     		 	 	 		    	  	  		  	 		  			 	   				 	  	   			 			 	 	   	  		 			  	 	 			  	 	  	   			 				 					   	 	   	 			 	 	  	  			  	
// 716F6B30598BA30945D84485E61C1027
void f0_6(int A_cmd_0, int A_magic_4) {
   double Ld_12;
   for (int pos_8 = OrdersTotal() - 1; pos_8 >= 0; pos_8--) {
      OrderSelect(pos_8, SELECT_BY_POS, MODE_TRADES);
      if (OrderSymbol() == Symbol() && OrderMagicNumber() == A_magic_4) {
         Ld_12 = 0;
         if (OrderType() == OP_BUY && A_cmd_0 == OP_BUY) {
            Ld_12 = OrderClose(OrderTicket(), OrderLots(), Bid, 3, Blue);
            if (Ld_12 > 0.0)
               if (Gi_380) f0_13("Close_BUY_" + DoubleToStr(OrderTicket(), 0));
         }
         if (OrderType() == OP_SELL && A_cmd_0 == OP_SELL) {
            Ld_12 = OrderClose(OrderTicket(), OrderLots(), Ask, 3, Red);
            if (Ld_12 > 0.0)
               if (Gi_380) f0_13("Close_SELL_" + DoubleToStr(OrderTicket(), 0));
         }
         if (OrderType() == A_cmd_0 && A_cmd_0 >= OP_BUYLIMIT) OrderDelete(OrderTicket());
      }
   }
}
	 		 		  	 		 		    				 	  	     		 				 							    			 			  			 			 	   	   			 	  	  	   	 		 	  		 			 	  			  					  	 	 			 			 	 				  	 	
// 6A3476421FE365B09A63ECA600A566E4
void f0_5(int A_magic_0) {
   double Ld_unused_8;
   for (int pos_4 = OrdersTotal() - 1; pos_4 >= 0; pos_4--) {
      OrderSelect(pos_4, SELECT_BY_POS, MODE_TRADES);
      if (OrderSymbol() == Symbol() && OrderMagicNumber() == A_magic_0) {
         Ld_unused_8 = 0;
         if (OrderType() == OP_BUY && Bid - OrderOpenPrice() >= AveraPlus_TP * Gd_400 && AveraPlus_TP > 0) Ld_unused_8 = OrderClose(OrderTicket(), OrderLots(), Bid, 3, Blue);
         if (OrderType() == OP_SELL && OrderOpenPrice() - Ask >= AveraPlus_TP * Gd_400 && AveraPlus_TP > 0) Ld_unused_8 = OrderClose(OrderTicket(), OrderLots(), Ask, 3, Red);
         if (OrderType() == OP_BUY && OrderOpenPrice() - Ask >= AveraPlus_SL * Gd_400 && AveraPlus_SL > 0) Ld_unused_8 = OrderClose(OrderTicket(), OrderLots(), Bid, 3, Blue);
         if (OrderType() == OP_SELL && Bid - OrderOpenPrice() >= AveraPlus_SL * Gd_400 && AveraPlus_SL > 0) Ld_unused_8 = OrderClose(OrderTicket(), OrderLots(), Ask, 3, Red);
      }
   }
}
	 		   			 			  	   	   		  					 		      			           				 	    				 		 	  	    	   		    		  		  	 	  	 	 	     		   	 	 		    				 	 			 	 	 
// 1673448EE7064C989D02579C534F6B66
bool f0_1() {
   /*if (Acount_Number != AccountNumber() && Acount_Number != 2096562384 && (!IsTesting()) && (!IsDemo())) {
      Comment("ONLY DEMO ACCOUNT PLEASE INSERT CODE");
      return (FALSE);
   }*/
   return (TRUE);
}
			         		 	 	 		  	   				  		    				 	  			 	   	  	  	 				 		   			 	 					  	 		 			 	   		 			    	 			  	  	 					 				 		  	 	  	  	
// 5FC732311905CB27E82D67F4F6511F7F
bool f0_4() {
   /*int str2time_0 = StrToTime(Gs_80);
   if (TimeCurrent() > str2time_0) {
      Alert("Expert Advisor sudah expired");
      return (FALSE);
   }*/
   return (TRUE);
}
	  		  					 	  	 	     			  				  		      	      	 	   		 			     	 	 		   		      	 		  	  	  			   	  					    		    	    	     	 	 	 	 			 	 
// C0E36F600151F785B9BE4CD446CB6655
void f0_11(int Ai_0, string As_4, string As_12) {
   int Li_20;
   int Li_24;
   switch (Ai_0) {
   case 1:
      Li_20 = 40;
      Li_24 = 120;
      break;
   case 2:
      Li_20 = 40;
      Li_24 = 135;
      break;
   case 3:
      Li_20 = 40;
      Li_24 = 150;
      break;
   case 4:
      Li_20 = 40;
      Li_24 = 165;
      break;
   case 5:
      Li_20 = 40;
      Li_24 = 180;
      break;
   case 6:
      Li_20 = 800;
      Li_24 = 2;
      break;
   case 7:
      Li_20 = 40;
      Li_24 = 210;
      break;
   case 8:
      Li_20 = 40;
      Li_24 = 225;
      break;
   case 9:
      Li_20 = 40;
      Li_24 = 240;
      break;
   case 10:
      Li_20 = 40;
      Li_24 = 195;
      break;
   case 11:
      Li_20 = 40;
      Li_24 = 210;
      break;
   case 12:
      Li_20 = 40;
      Li_24 = 225;
      break;
   case 13:
      Li_20 = 40;
      Li_24 = 240;
      break;
   case 14:
      Li_20 = 40;
      Li_24 = 255;
      break;
   case 15:
      Li_20 = 40;
      Li_24 = 270;
      break;
   case 16:
      Li_20 = 40;
      Li_24 = 285;
      break;
   case 17:
      Li_20 = 40;
      Li_24 = 300;
   }
   f0_12("baris" + Ai_0, As_4, 10, Li_20, Li_24, Green, 0);
   f0_12("baris_" + Ai_0, ":", 10, Li_20 + 80, Li_24, Black, 0);
   f0_12("baris-" + Ai_0, As_12, 10, Li_20 + 90, Li_24, Black, 0);
   string text_32 = "BAMS-BUNG Finnal V2";
   if (ObjectFind("CC2") != 0) ObjectCreate("CC2", OBJ_LABEL, 0, 0, 0);
   ObjectSet("CC2", OBJPROP_CORNER, 4);
   ObjectSet("CC2", OBJPROP_XDISTANCE, 3);
   ObjectSet("CC2", OBJPROP_YDISTANCE, 13);
   ObjectSet("CC2", OBJPROP_BACK, TRUE);
   ObjectSetText("CC2", text_32, 28, "Stencil", Gold);
   string text_40 = "Expert Advisor";
   if (ObjectFind("CC3") != 0) ObjectCreate("CC3", OBJ_LABEL, 0, 0, 0);
   ObjectSet("CC3", OBJPROP_CORNER, 4);
   ObjectSet("CC3", OBJPROP_XDISTANCE, 85);
   ObjectSet("CC3", OBJPROP_YDISTANCE, 76);
   ObjectSet("CC3", OBJPROP_BACK, TRUE);
   ObjectSetText("CC3", text_40, 20, "Georgia", Black);
   string text_48 = "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC";
   if (ObjectFind("CC4") != 0) ObjectCreate("CC4", OBJ_LABEL, 0, 0, 0);
   ObjectSet("CC4", OBJPROP_CORNER, 12);
   ObjectSet("CC4", OBJPROP_XDISTANCE, 0);
   ObjectSet("CC4", OBJPROP_YDISTANCE, 50);
   ObjectSet("CC4", OBJPROP_BACK, FALSE);
   ObjectSetText("CC4", text_48, 8, "Wingdings", MistyRose);
   string text_56 = "n";
   if (ObjectFind("CC5") != 0) ObjectCreate("CC5", OBJ_LABEL, 0, 0, 0);
   ObjectSet("CC5", OBJPROP_CORNER, 4);
   ObjectSet("CC5", OBJPROP_XDISTANCE, 150);
   ObjectSet("CC5", OBJPROP_YDISTANCE, 45);
   ObjectSet("CC5", OBJPROP_BACK, TRUE);
   ObjectSetText("CC5", text_56, 200, "Wingdings", White);
   string text_64 = "n";
   if (ObjectFind("CC6") != 0) ObjectCreate("CC6", OBJ_LABEL, 0, 0, 0);
   ObjectSet("CC6", OBJPROP_CORNER, 4);
   ObjectSet("CC6", OBJPROP_XDISTANCE, 0);
   ObjectSet("CC6", OBJPROP_YDISTANCE, 45);
   ObjectSet("CC6", OBJPROP_BACK, TRUE);
   ObjectSetText("CC6", text_64, 200, "Wingdings", White);
   string text_72 = "____________";
   if (ObjectFind("CC7") != 0) ObjectCreate("CC7", OBJ_LABEL, 0, 0, 0);
   ObjectSet("CC7", OBJPROP_CORNER, 12);
   ObjectSet("CC7", OBJPROP_XDISTANCE, 85);
   ObjectSet("CC7", OBJPROP_YDISTANCE, 76);
   ObjectSet("CC7", OBJPROP_BACK, TRUE);
   ObjectSetText("CC7", text_72, 20, "Arial", MistyRose);
   string text_80 = "================================================";
   if (ObjectFind("CC8") != 0) ObjectCreate("CC8", OBJ_LABEL, 0, 0, 0);
   ObjectSet("CC8", OBJPROP_CORNER, 4);
   ObjectSet("CC8", OBJPROP_XDISTANCE, 30);
   ObjectSet("CC8", OBJPROP_YDISTANCE, 194);
   ObjectSet("CC8", OBJPROP_BACK, TRUE);
   ObjectSetText("CC8", text_80, 8, "Arial", Indigo);
   string text_88 = "================================================";
   if (ObjectFind("CC9") != 0) ObjectCreate("CC9", OBJ_LABEL, 0, 0, 0);
   ObjectSet("CC9", OBJPROP_CORNER, 4);
   ObjectSet("CC9", OBJPROP_XDISTANCE, 30);
   ObjectSet("CC9", OBJPROP_YDISTANCE, 110);
   ObjectSet("CC9", OBJPROP_BACK, TRUE);
   ObjectSetText("CC9", text_88, 8, "Arial", Indigo);
   string text_96 = "n";
   if (ObjectFind("CC10") != 0) ObjectCreate("CC10", OBJ_LABEL, 0, 0, 0);
   ObjectSet("CC10", OBJPROP_CORNER, 4);
   ObjectSet("CC10", OBJPROP_XDISTANCE, 156);
   ObjectSet("CC10", OBJPROP_YDISTANCE, 11);
   ObjectSet("CC10", OBJPROP_BACK, TRUE);
   ObjectSetText("CC10", text_96, 200, "Wingdings", Red);
   string text_104 = "n";
   if (ObjectFind("CC11") != 0) ObjectCreate("CC11", OBJ_LABEL, 0, 0, 0);
   ObjectSet("CC11", OBJPROP_CORNER, 4);
   ObjectSet("CC11", OBJPROP_XDISTANCE, 11);
   ObjectSet("CC11", OBJPROP_YDISTANCE, 11);
   ObjectSet("CC11", OBJPROP_BACK, TRUE);
   ObjectSetText("CC11", text_104, 200, "Wingdings", Red);
   string text_112 = "================================================";
   if (ObjectFind("CC12") != 0) ObjectCreate("CC12", OBJ_LABEL, 0, 0, 0);
   ObjectSet("CC12", OBJPROP_CORNER, 4);
   ObjectSet("CC12", OBJPROP_XDISTANCE, 30);
   ObjectSet("CC12", OBJPROP_YDISTANCE, 254);
   ObjectSet("CC12", OBJPROP_BACK, FALSE);
   ObjectSetText("CC12", text_112, 8, "Arial", Indigo);
}
					  		  	 	  		      	    								    			     	  	   	 				   			 	 				 		   		 	 		 	   	  	     	    			   	 	    			  	   			 	 	  				 	 
// D2986AC8CB6BD55892099C1FFD6B1F6F
void f0_12(string A_name_0, string A_text_8, int A_fontsize_16, int A_x_20, int A_y_24, color A_color_28, int A_corner_32) {
   if (ObjectFind(A_name_0) < 0) ObjectCreate(A_name_0, OBJ_LABEL, 0, 0, 0, 0, 0);
   ObjectSet(A_name_0, OBJPROP_CORNER, A_corner_32);
   ObjectSet(A_name_0, OBJPROP_XDISTANCE, A_x_20);
   ObjectSet(A_name_0, OBJPROP_YDISTANCE, A_y_24);
   ObjectSetText(A_name_0, A_text_8, A_fontsize_16, "Cooper Black", A_color_28);
}
	 				  		 	   		    	 			    	 	 				 	  		 	 	    		 						  	  		    	 	 	  	  	 			        			   			 	 		  	   	 	 		 	    	  		     				    
// D7BA9BBFDA42B9657F14EE37EF76150B
void f0_13(string A_name_0) {
   if (ObjectFind(A_name_0) < 0) ObjectCreate(A_name_0, OBJ_LABEL, 0, 0, 0, 0, 0);
   ObjectSet(A_name_0, OBJPROP_CORNER, 3);
   ObjectSet(A_name_0, OBJPROP_XDISTANCE, 20);
   ObjectSet(A_name_0, OBJPROP_YDISTANCE, 20);
   ObjectSetText(A_name_0, A_name_0, 12, "Cooper Black", Gold);
   string name_8 = Symbol() + "_" + A_name_0 + ".gif";
   int file_16 = FileOpen(name_8, FILE_CSV|FILE_READ);
   if (file_16 < 1) {
      if (!WindowScreenShot(name_8, 640, 480)) Print("eror scren chart " + GetLastError());
      else {
         Print("capture!");
         PlaySound("Alert.wav");
      }
   }
   ObjectDelete(A_name_0);
}
	  	 		 					 			 	 							 	   	  	 			   					  	  					 	  		   		 	 	     		     	    	 	 					 		 	 			  		  							   	 		   		 	  	 	  	  
// AD05F78187C942F9DD521605FA81F1BA
double f0_8(double Ad_0) {
   double Ld_8 = MarketInfo(Symbol(), MODE_MINLOT);
   double Ld_16 = MarketInfo(Symbol(), MODE_MAXLOT);
   if (Ad_0 < Ld_8) Ad_0 = Ld_8;
   if (Ad_0 > Ld_16) Ad_0 = Ld_16;
   return (NormalizeDouble(Ad_0, 2));
}